/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/cocktail_mit_camera_2_final_final_v3_wirklich_wirklich.gltf"
  );

  const { actions, mixer } = useAnimations(animations, group);

  console.log({ actions });

  useEffect(() => {
    actions.schirmAction.play();
    actions["Cylinder.001Action"].play();
    actions["Cylinder.002Action"].play();
    actions.IcosphereAction.play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="BezierCircle"
          position={[0, 2.46, 0]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={1.28}
        />
        <PerspectiveCamera
          name="Camera"
          makeDefault={true}
          far={100}
          near={0.1}
          fov={22.9}
          position={[12.8, 6.9, 0]}
          rotation={[-Math.PI / 2, 1.2, Math.PI / 2]}
        />
        <pointLight
          name="Light"
          intensity={1}
          decay={2}
          position={[0.02, 12.37, 0.02]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="lemon"
          geometry={nodes.lemon.geometry}
          material={materials.cocktail_tex}
          position={[0, 2.55, -1.04]}
          scale={[1.44, 1, 1]}
        />
        <mesh
          name="liq_1"
          geometry={nodes.liq_1.geometry}
          material={materials.white}
          position={[0, 0.41, 0]}
        />
        <mesh
          name="liq_2"
          geometry={nodes.liq_2.geometry}
          material={materials.orange}
          position={[0, 1.52, 0]}
        />
        <mesh
          name="liq_3"
          geometry={nodes.liq_3.geometry}
          material={materials.red}
          position={[0, 2.43, 0]}
        />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials.blue}
          position={[0, -0.69, 0]}
          scale={[89.6, 89.6, 37.46]}
        />
        <mesh
          name="schirm"
          geometry={nodes.schirm.geometry}
          material={materials.cocktail_tex}
          position={[-1.04, 3.56, -1.09]}
        />
        <mesh
          name="straw"
          geometry={nodes.straw.geometry}
          material={materials.cocktail_tex}
          rotation={[0.29, 0, 0]}
        />
        <mesh
          name="Icosphere"
          geometry={nodes.Icosphere.geometry}
          material={materials.red}
          position={[-1.28, 2.46, 0]}
          scale={0.72}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cocktail_mit_camera_2_final_final_v3_wirklich_wirklich.gltf");
