/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations, cameras } =
    useGLTF("/cocktail_all.gltf");
  const { actions } = useAnimations(animations, group);
  console.log({ cameras });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="BezierCircle"
          position={[0, 2.46, 0]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={1.28}
        />
        <mesh
          name="straw"
          geometry={nodes.straw.geometry}
          material={materials.cocktail_tex}
          rotation={[0.29, 0, 0]}
        />
        <mesh
          name="lemon"
          geometry={nodes.lemon.geometry}
          material={materials.cocktail_tex}
          position={[0, 2.55, -1.04]}
          scale={[1.44, 1, 1]}
        />
        <mesh
          name="liq_2"
          geometry={nodes.liq_2.geometry}
          material={materials.orange}
          position={[0, 1.52, 0]}
        />
        <mesh
          name="liq_3"
          geometry={nodes.liq_3.geometry}
          material={materials.red}
          position={[0, 2.43, 0]}
        />
        <mesh
          name="liq_1"
          geometry={nodes.liq_1.geometry}
          material={materials.white}
          position={[0, 0.41, 0]}
        />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials.blue}
          position={[0, -0.69, 0]}
          scale={[89.6, 89.6, 37.46]}
        />
        <mesh
          name="schirm"
          geometry={nodes.schirm.geometry}
          material={materials.cocktail_tex}
          position={[-1.04, 3.56, -1.09]}
        />
        <mesh
          name="Icosphere"
          geometry={nodes.Icosphere.geometry}
          material={nodes.Icosphere.material}
          position={[-1.28, 2.46, 0]}
          scale={0.72}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cocktail_all.gltf");
